/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as SpecialitiesRouteImport } from './routes/specialities'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthLanguageRouteImport } from './routes/auth.language'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthProfileRouteImport } from './routes/auth.profile'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as BookingDoctorIdRouteImport } from './routes/booking.$doctorId'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorAnalyticsRouteImport } from './routes/doctor.analytics'
import { Route as DoctorCalendarRouteImport } from './routes/doctor.calendar'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorQueueRouteImport } from './routes/doctor.queue'
import { Route as DoctorReviewsRouteImport } from './routes/doctor.reviews'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorSettingsRouteImport } from './routes/doctor.settings'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors.$doctorId'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as PatientArticlesRouteImport } from './routes/patient.articles'
import { Route as PatientCareAiRouteImport } from './routes/patient.care-ai'
import { Route as PatientCompareRouteImport } from './routes/patient.compare'
import { Route as PatientConsultRouteImport } from './routes/patient.consult'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientDoctorsRouteImport } from './routes/patient.doctors'
import { Route as PatientFamilyRouteImport } from './routes/patient.family'
import { Route as PatientFavoritesRouteImport } from './routes/patient.favorites'
import { Route as PatientFeedRouteImport } from './routes/patient.feed'
import { Route as PatientHelpRouteImport } from './routes/patient.help'
import { Route as PatientLabTestsRouteImport } from './routes/patient.lab-tests'
import { Route as PatientMedicinesRouteImport } from './routes/patient.medicines'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientQueueRouteImport } from './routes/patient.queue'
import { Route as PatientSearchRouteImport } from './routes/patient.search'
import { Route as PatientSubscriptionsRouteImport } from './routes/patient.subscriptions'
import { Route as PatientSurgeriesRouteImport } from './routes/patient.surgeries'
import { Route as PaymentDoctorIdRouteImport } from './routes/payment.$doctorId'
import { Route as DoctorPatientsIndexRouteImport } from './routes/doctor.patients.index'
import { Route as PatientArticlesIndexRouteImport } from './routes/patient.articles.index'
import { Route as PatientArticlesArticleIdRouteImport } from './routes/patient.articles.$articleId'
import { Route as PatientDoctorDoctorIdRouteImport } from './routes/patient.doctor.$doctorId'
import { Route as PatientPaymentCheckoutRouteImport } from './routes/patient.payment.checkout'
import { Route as PatientPaymentHistoryRouteImport } from './routes/patient.payment.history'
import { Route as DoctorPatientsPatientIdIndexRouteImport } from './routes/doctor.patients.$patientId.index'
import { Route as DoctorPatientsPatientIdPrescribeRouteImport } from './routes/doctor.patients.$patientId.prescribe'
import { Route as PatientDoctorDoctorIdBookRouteImport } from './routes/patient.doctor.$doctorId.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialitiesRoute = SpecialitiesRouteImport.update({
  id: '/specialities',
  path: '/specialities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthLanguageRoute = AuthLanguageRouteImport.update({
  id: '/auth/language',
  path: '/auth/language',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingDoctorIdRoute = BookingDoctorIdRouteImport.update({
  id: '/booking/$doctorId',
  path: '/booking/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAnalyticsRoute = DoctorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorCalendarRoute = DoctorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorQueueRoute = DoctorQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorReviewsRoute = DoctorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientArticlesRoute = PatientArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCareAiRoute = PatientCareAiRouteImport.update({
  id: '/care-ai',
  path: '/care-ai',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCompareRoute = PatientCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => PatientRoute,
} as any)
const PatientConsultRoute = PatientConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDoctorsRoute = PatientDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => PatientRoute,
} as any)
const PatientFamilyRoute = PatientFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => PatientRoute,
} as any)
const PatientFavoritesRoute = PatientFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => PatientRoute,
} as any)
const PatientFeedRoute = PatientFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHelpRoute = PatientHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PatientRoute,
} as any)
const PatientLabTestsRoute = PatientLabTestsRouteImport.update({
  id: '/lab-tests',
  path: '/lab-tests',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicinesRoute = PatientMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientQueueRoute = PatientQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSearchRoute = PatientSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSubscriptionsRoute = PatientSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSurgeriesRoute = PatientSurgeriesRouteImport.update({
  id: '/surgeries',
  path: '/surgeries',
  getParentRoute: () => PatientRoute,
} as any)
const PaymentDoctorIdRoute = PaymentDoctorIdRouteImport.update({
  id: '/payment/$doctorId',
  path: '/payment/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsIndexRoute = DoctorPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => DoctorRoute,
} as any)
const PatientArticlesIndexRoute = PatientArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientArticlesRoute,
} as any)
const PatientArticlesArticleIdRoute =
  PatientArticlesArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => PatientArticlesRoute,
  } as any)
const PatientDoctorDoctorIdRoute = PatientDoctorDoctorIdRouteImport.update({
  id: '/doctor/$doctorId',
  path: '/doctor/$doctorId',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPaymentCheckoutRoute = PatientPaymentCheckoutRouteImport.update({
  id: '/payment/checkout',
  path: '/payment/checkout',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPaymentHistoryRoute = PatientPaymentHistoryRouteImport.update({
  id: '/payment/history',
  path: '/payment/history',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorPatientsPatientIdIndexRoute =
  DoctorPatientsPatientIdIndexRouteImport.update({
    id: '/patients/$patientId/',
    path: '/patients/$patientId/',
    getParentRoute: () => DoctorRoute,
  } as any)
const DoctorPatientsPatientIdPrescribeRoute =
  DoctorPatientsPatientIdPrescribeRouteImport.update({
    id: '/patients/$patientId/prescribe',
    path: '/patients/$patientId/prescribe',
    getParentRoute: () => DoctorRoute,
  } as any)
const PatientDoctorDoctorIdBookRoute =
  PatientDoctorDoctorIdBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => PatientDoctorDoctorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking-success': typeof BookingSuccessRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/specialities': typeof SpecialitiesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/language': typeof AuthLanguageRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/calendar': typeof DoctorCalendarRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/articles': typeof PatientArticlesRouteWithChildren
  '/patient/care-ai': typeof PatientCareAiRoute
  '/patient/compare': typeof PatientCompareRoute
  '/patient/consult': typeof PatientConsultRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/family': typeof PatientFamilyRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/feed': typeof PatientFeedRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/lab-tests': typeof PatientLabTestsRoute
  '/patient/medicines': typeof PatientMedicinesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/patient/search': typeof PatientSearchRoute
  '/patient/subscriptions': typeof PatientSubscriptionsRoute
  '/patient/surgeries': typeof PatientSurgeriesRoute
  '/payment/$doctorId': typeof PaymentDoctorIdRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/articles/$articleId': typeof PatientArticlesArticleIdRoute
  '/patient/doctor/$doctorId': typeof PatientDoctorDoctorIdRouteWithChildren
  '/patient/payment/checkout': typeof PatientPaymentCheckoutRoute
  '/patient/payment/history': typeof PatientPaymentHistoryRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
  '/patient/articles/': typeof PatientArticlesIndexRoute
  '/doctor/patients/$patientId/prescribe': typeof DoctorPatientsPatientIdPrescribeRoute
  '/patient/doctor/$doctorId/book': typeof PatientDoctorDoctorIdBookRoute
  '/doctor/patients/$patientId/': typeof DoctorPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking-success': typeof BookingSuccessRoute
  '/specialities': typeof SpecialitiesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/language': typeof AuthLanguageRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/calendar': typeof DoctorCalendarRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/care-ai': typeof PatientCareAiRoute
  '/patient/compare': typeof PatientCompareRoute
  '/patient/consult': typeof PatientConsultRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/family': typeof PatientFamilyRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/feed': typeof PatientFeedRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/lab-tests': typeof PatientLabTestsRoute
  '/patient/medicines': typeof PatientMedicinesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/patient/search': typeof PatientSearchRoute
  '/patient/subscriptions': typeof PatientSubscriptionsRoute
  '/patient/surgeries': typeof PatientSurgeriesRoute
  '/payment/$doctorId': typeof PaymentDoctorIdRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/patient': typeof PatientIndexRoute
  '/patient/articles/$articleId': typeof PatientArticlesArticleIdRoute
  '/patient/doctor/$doctorId': typeof PatientDoctorDoctorIdRouteWithChildren
  '/patient/payment/checkout': typeof PatientPaymentCheckoutRoute
  '/patient/payment/history': typeof PatientPaymentHistoryRoute
  '/doctor/patients': typeof DoctorPatientsIndexRoute
  '/patient/articles': typeof PatientArticlesIndexRoute
  '/doctor/patients/$patientId/prescribe': typeof DoctorPatientsPatientIdPrescribeRoute
  '/patient/doctor/$doctorId/book': typeof PatientDoctorDoctorIdBookRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking-success': typeof BookingSuccessRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/specialities': typeof SpecialitiesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/language': typeof AuthLanguageRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$doctorId': typeof BookingDoctorIdRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/calendar': typeof DoctorCalendarRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/articles': typeof PatientArticlesRouteWithChildren
  '/patient/care-ai': typeof PatientCareAiRoute
  '/patient/compare': typeof PatientCompareRoute
  '/patient/consult': typeof PatientConsultRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/doctors': typeof PatientDoctorsRoute
  '/patient/family': typeof PatientFamilyRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/feed': typeof PatientFeedRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/lab-tests': typeof PatientLabTestsRoute
  '/patient/medicines': typeof PatientMedicinesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/patient/search': typeof PatientSearchRoute
  '/patient/subscriptions': typeof PatientSubscriptionsRoute
  '/patient/surgeries': typeof PatientSurgeriesRoute
  '/payment/$doctorId': typeof PaymentDoctorIdRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/articles/$articleId': typeof PatientArticlesArticleIdRoute
  '/patient/doctor/$doctorId': typeof PatientDoctorDoctorIdRouteWithChildren
  '/patient/payment/checkout': typeof PatientPaymentCheckoutRoute
  '/patient/payment/history': typeof PatientPaymentHistoryRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
  '/patient/articles/': typeof PatientArticlesIndexRoute
  '/doctor/patients/$patientId/prescribe': typeof DoctorPatientsPatientIdPrescribeRoute
  '/patient/doctor/$doctorId/book': typeof PatientDoctorDoctorIdBookRoute
  '/doctor/patients/$patientId/': typeof DoctorPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/booking-success'
    | '/doctor'
    | '/patient'
    | '/specialities'
    | '/admin/appointments'
    | '/admin/cms'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/language'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/verify'
    | '/booking/$doctorId'
    | '/doctor/analytics'
    | '/doctor/calendar'
    | '/doctor/prescriptions'
    | '/doctor/queue'
    | '/doctor/reviews'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/doctors/$doctorId'
    | '/patient/appointments'
    | '/patient/articles'
    | '/patient/care-ai'
    | '/patient/compare'
    | '/patient/consult'
    | '/patient/dashboard'
    | '/patient/doctors'
    | '/patient/family'
    | '/patient/favorites'
    | '/patient/feed'
    | '/patient/help'
    | '/patient/lab-tests'
    | '/patient/medicines'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/queue'
    | '/patient/search'
    | '/patient/subscriptions'
    | '/patient/surgeries'
    | '/payment/$doctorId'
    | '/admin/'
    | '/doctor/'
    | '/doctors/'
    | '/patient/'
    | '/patient/articles/$articleId'
    | '/patient/doctor/$doctorId'
    | '/patient/payment/checkout'
    | '/patient/payment/history'
    | '/doctor/patients/'
    | '/patient/articles/'
    | '/doctor/patients/$patientId/prescribe'
    | '/patient/doctor/$doctorId/book'
    | '/doctor/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking-success'
    | '/specialities'
    | '/admin/appointments'
    | '/admin/cms'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/language'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/verify'
    | '/booking/$doctorId'
    | '/doctor/analytics'
    | '/doctor/calendar'
    | '/doctor/prescriptions'
    | '/doctor/queue'
    | '/doctor/reviews'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/doctors/$doctorId'
    | '/patient/appointments'
    | '/patient/care-ai'
    | '/patient/compare'
    | '/patient/consult'
    | '/patient/dashboard'
    | '/patient/doctors'
    | '/patient/family'
    | '/patient/favorites'
    | '/patient/feed'
    | '/patient/help'
    | '/patient/lab-tests'
    | '/patient/medicines'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/queue'
    | '/patient/search'
    | '/patient/subscriptions'
    | '/patient/surgeries'
    | '/payment/$doctorId'
    | '/admin'
    | '/doctor'
    | '/doctors'
    | '/patient'
    | '/patient/articles/$articleId'
    | '/patient/doctor/$doctorId'
    | '/patient/payment/checkout'
    | '/patient/payment/history'
    | '/doctor/patients'
    | '/patient/articles'
    | '/doctor/patients/$patientId/prescribe'
    | '/patient/doctor/$doctorId/book'
    | '/doctor/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/booking-success'
    | '/doctor'
    | '/patient'
    | '/specialities'
    | '/admin/appointments'
    | '/admin/cms'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/language'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/verify'
    | '/booking/$doctorId'
    | '/doctor/analytics'
    | '/doctor/calendar'
    | '/doctor/prescriptions'
    | '/doctor/queue'
    | '/doctor/reviews'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/doctors/$doctorId'
    | '/patient/appointments'
    | '/patient/articles'
    | '/patient/care-ai'
    | '/patient/compare'
    | '/patient/consult'
    | '/patient/dashboard'
    | '/patient/doctors'
    | '/patient/family'
    | '/patient/favorites'
    | '/patient/feed'
    | '/patient/help'
    | '/patient/lab-tests'
    | '/patient/medicines'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/queue'
    | '/patient/search'
    | '/patient/subscriptions'
    | '/patient/surgeries'
    | '/payment/$doctorId'
    | '/admin/'
    | '/doctor/'
    | '/doctors/'
    | '/patient/'
    | '/patient/articles/$articleId'
    | '/patient/doctor/$doctorId'
    | '/patient/payment/checkout'
    | '/patient/payment/history'
    | '/doctor/patients/'
    | '/patient/articles/'
    | '/doctor/patients/$patientId/prescribe'
    | '/patient/doctor/$doctorId/book'
    | '/doctor/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingSuccessRoute: typeof BookingSuccessRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  SpecialitiesRoute: typeof SpecialitiesRoute
  AuthLanguageRoute: typeof AuthLanguageRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  BookingDoctorIdRoute: typeof BookingDoctorIdRoute
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
  PaymentDoctorIdRoute: typeof PaymentDoctorIdRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialities': {
      id: '/specialities'
      path: '/specialities'
      fullPath: '/specialities'
      preLoaderRoute: typeof SpecialitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/language': {
      id: '/auth/language'
      path: '/auth/language'
      fullPath: '/auth/language'
      preLoaderRoute: typeof AuthLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$doctorId': {
      id: '/booking/$doctorId'
      path: '/booking/$doctorId'
      fullPath: '/booking/$doctorId'
      preLoaderRoute: typeof BookingDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/calendar': {
      id: '/doctor/calendar'
      path: '/calendar'
      fullPath: '/doctor/calendar'
      preLoaderRoute: typeof DoctorCalendarRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/queue': {
      id: '/doctor/queue'
      path: '/queue'
      fullPath: '/doctor/queue'
      preLoaderRoute: typeof DoctorQueueRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/reviews': {
      id: '/doctor/reviews'
      path: '/reviews'
      fullPath: '/doctor/reviews'
      preLoaderRoute: typeof DoctorReviewsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/articles': {
      id: '/patient/articles'
      path: '/articles'
      fullPath: '/patient/articles'
      preLoaderRoute: typeof PatientArticlesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/care-ai': {
      id: '/patient/care-ai'
      path: '/care-ai'
      fullPath: '/patient/care-ai'
      preLoaderRoute: typeof PatientCareAiRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/compare': {
      id: '/patient/compare'
      path: '/compare'
      fullPath: '/patient/compare'
      preLoaderRoute: typeof PatientCompareRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/consult': {
      id: '/patient/consult'
      path: '/consult'
      fullPath: '/patient/consult'
      preLoaderRoute: typeof PatientConsultRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/doctors': {
      id: '/patient/doctors'
      path: '/doctors'
      fullPath: '/patient/doctors'
      preLoaderRoute: typeof PatientDoctorsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/family': {
      id: '/patient/family'
      path: '/family'
      fullPath: '/patient/family'
      preLoaderRoute: typeof PatientFamilyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/favorites': {
      id: '/patient/favorites'
      path: '/favorites'
      fullPath: '/patient/favorites'
      preLoaderRoute: typeof PatientFavoritesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/feed': {
      id: '/patient/feed'
      path: '/feed'
      fullPath: '/patient/feed'
      preLoaderRoute: typeof PatientFeedRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/help': {
      id: '/patient/help'
      path: '/help'
      fullPath: '/patient/help'
      preLoaderRoute: typeof PatientHelpRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/lab-tests': {
      id: '/patient/lab-tests'
      path: '/lab-tests'
      fullPath: '/patient/lab-tests'
      preLoaderRoute: typeof PatientLabTestsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medicines': {
      id: '/patient/medicines'
      path: '/medicines'
      fullPath: '/patient/medicines'
      preLoaderRoute: typeof PatientMedicinesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/queue': {
      id: '/patient/queue'
      path: '/queue'
      fullPath: '/patient/queue'
      preLoaderRoute: typeof PatientQueueRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/search': {
      id: '/patient/search'
      path: '/search'
      fullPath: '/patient/search'
      preLoaderRoute: typeof PatientSearchRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/subscriptions': {
      id: '/patient/subscriptions'
      path: '/subscriptions'
      fullPath: '/patient/subscriptions'
      preLoaderRoute: typeof PatientSubscriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/surgeries': {
      id: '/patient/surgeries'
      path: '/surgeries'
      fullPath: '/patient/surgeries'
      preLoaderRoute: typeof PatientSurgeriesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/payment/$doctorId': {
      id: '/payment/$doctorId'
      path: '/payment/$doctorId'
      fullPath: '/payment/$doctorId'
      preLoaderRoute: typeof PaymentDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/': {
      id: '/doctor/patients/'
      path: '/patients'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof DoctorPatientsIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/patient/articles/': {
      id: '/patient/articles/'
      path: '/'
      fullPath: '/patient/articles/'
      preLoaderRoute: typeof PatientArticlesIndexRouteImport
      parentRoute: typeof PatientArticlesRoute
    }
    '/patient/articles/$articleId': {
      id: '/patient/articles/$articleId'
      path: '/$articleId'
      fullPath: '/patient/articles/$articleId'
      preLoaderRoute: typeof PatientArticlesArticleIdRouteImport
      parentRoute: typeof PatientArticlesRoute
    }
    '/patient/doctor/$doctorId': {
      id: '/patient/doctor/$doctorId'
      path: '/doctor/$doctorId'
      fullPath: '/patient/doctor/$doctorId'
      preLoaderRoute: typeof PatientDoctorDoctorIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/payment/checkout': {
      id: '/patient/payment/checkout'
      path: '/payment/checkout'
      fullPath: '/patient/payment/checkout'
      preLoaderRoute: typeof PatientPaymentCheckoutRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/payment/history': {
      id: '/patient/payment/history'
      path: '/payment/history'
      fullPath: '/patient/payment/history'
      preLoaderRoute: typeof PatientPaymentHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/patients/$patientId/': {
      id: '/doctor/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/doctor/patients/$patientId/'
      preLoaderRoute: typeof DoctorPatientsPatientIdIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients/$patientId/prescribe': {
      id: '/doctor/patients/$patientId/prescribe'
      path: '/patients/$patientId/prescribe'
      fullPath: '/doctor/patients/$patientId/prescribe'
      preLoaderRoute: typeof DoctorPatientsPatientIdPrescribeRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/patient/doctor/$doctorId/book': {
      id: '/patient/doctor/$doctorId/book'
      path: '/book'
      fullPath: '/patient/doctor/$doctorId/book'
      preLoaderRoute: typeof PatientDoctorDoctorIdBookRouteImport
      parentRoute: typeof PatientDoctorDoctorIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorAnalyticsRoute: typeof DoctorAnalyticsRoute
  DoctorCalendarRoute: typeof DoctorCalendarRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorQueueRoute: typeof DoctorQueueRoute
  DoctorReviewsRoute: typeof DoctorReviewsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorPatientsIndexRoute: typeof DoctorPatientsIndexRoute
  DoctorPatientsPatientIdPrescribeRoute: typeof DoctorPatientsPatientIdPrescribeRoute
  DoctorPatientsPatientIdIndexRoute: typeof DoctorPatientsPatientIdIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAnalyticsRoute: DoctorAnalyticsRoute,
  DoctorCalendarRoute: DoctorCalendarRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorQueueRoute: DoctorQueueRoute,
  DoctorReviewsRoute: DoctorReviewsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorPatientsIndexRoute: DoctorPatientsIndexRoute,
  DoctorPatientsPatientIdPrescribeRoute: DoctorPatientsPatientIdPrescribeRoute,
  DoctorPatientsPatientIdIndexRoute: DoctorPatientsPatientIdIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientArticlesRouteChildren {
  PatientArticlesArticleIdRoute: typeof PatientArticlesArticleIdRoute
  PatientArticlesIndexRoute: typeof PatientArticlesIndexRoute
}

const PatientArticlesRouteChildren: PatientArticlesRouteChildren = {
  PatientArticlesArticleIdRoute: PatientArticlesArticleIdRoute,
  PatientArticlesIndexRoute: PatientArticlesIndexRoute,
}

const PatientArticlesRouteWithChildren = PatientArticlesRoute._addFileChildren(
  PatientArticlesRouteChildren,
)

interface PatientDoctorDoctorIdRouteChildren {
  PatientDoctorDoctorIdBookRoute: typeof PatientDoctorDoctorIdBookRoute
}

const PatientDoctorDoctorIdRouteChildren: PatientDoctorDoctorIdRouteChildren = {
  PatientDoctorDoctorIdBookRoute: PatientDoctorDoctorIdBookRoute,
}

const PatientDoctorDoctorIdRouteWithChildren =
  PatientDoctorDoctorIdRoute._addFileChildren(
    PatientDoctorDoctorIdRouteChildren,
  )

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientArticlesRoute: typeof PatientArticlesRouteWithChildren
  PatientCareAiRoute: typeof PatientCareAiRoute
  PatientCompareRoute: typeof PatientCompareRoute
  PatientConsultRoute: typeof PatientConsultRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientDoctorsRoute: typeof PatientDoctorsRoute
  PatientFamilyRoute: typeof PatientFamilyRoute
  PatientFavoritesRoute: typeof PatientFavoritesRoute
  PatientFeedRoute: typeof PatientFeedRoute
  PatientHelpRoute: typeof PatientHelpRoute
  PatientLabTestsRoute: typeof PatientLabTestsRoute
  PatientMedicinesRoute: typeof PatientMedicinesRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientQueueRoute: typeof PatientQueueRoute
  PatientSearchRoute: typeof PatientSearchRoute
  PatientSubscriptionsRoute: typeof PatientSubscriptionsRoute
  PatientSurgeriesRoute: typeof PatientSurgeriesRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientDoctorDoctorIdRoute: typeof PatientDoctorDoctorIdRouteWithChildren
  PatientPaymentCheckoutRoute: typeof PatientPaymentCheckoutRoute
  PatientPaymentHistoryRoute: typeof PatientPaymentHistoryRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientArticlesRoute: PatientArticlesRouteWithChildren,
  PatientCareAiRoute: PatientCareAiRoute,
  PatientCompareRoute: PatientCompareRoute,
  PatientConsultRoute: PatientConsultRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientDoctorsRoute: PatientDoctorsRoute,
  PatientFamilyRoute: PatientFamilyRoute,
  PatientFavoritesRoute: PatientFavoritesRoute,
  PatientFeedRoute: PatientFeedRoute,
  PatientHelpRoute: PatientHelpRoute,
  PatientLabTestsRoute: PatientLabTestsRoute,
  PatientMedicinesRoute: PatientMedicinesRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientQueueRoute: PatientQueueRoute,
  PatientSearchRoute: PatientSearchRoute,
  PatientSubscriptionsRoute: PatientSubscriptionsRoute,
  PatientSurgeriesRoute: PatientSurgeriesRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientDoctorDoctorIdRoute: PatientDoctorDoctorIdRouteWithChildren,
  PatientPaymentCheckoutRoute: PatientPaymentCheckoutRoute,
  PatientPaymentHistoryRoute: PatientPaymentHistoryRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingSuccessRoute: BookingSuccessRoute,
  DoctorRoute: DoctorRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  SpecialitiesRoute: SpecialitiesRoute,
  AuthLanguageRoute: AuthLanguageRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  BookingDoctorIdRoute: BookingDoctorIdRoute,
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
  PaymentDoctorIdRoute: PaymentDoctorIdRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
